//  1: Hit enemy
//  2: Kamikaze
//  3: Barrel break
//  4: Saw run
//  5: Needlejump
//  6: Heavy Hopscotch (Boss)
//  7: Heavy Skydiving (Boss) _[Scrapped]_
//  8: Airblast
//  9: Maths
// 10: Movement
// 11: Flood
// 12: Demo DodgeBall (Boss) _[Scrapped]_
// 13: Demo BBall (Boss)
// 14: Hugging Heavy (Boss)
// 15: Simon Says
// 16: Least Wins (Boss)
// 17: Spycrab


#define GAME_BOSS_LEAST_WINS 16
